### ISSUE TITLE
Strange data-loss bug

### ISSUE THREAD

**Issue by alphapapa** [Fanael/persistent-scratch#10] opened 2017-07-23 19:15 UTC
As mentioned in https://github.com/Fanael/persistent-scratch/issues/8#issuecomment-317265930

I have been experiencing a bug in which the scratch file gets emptied and I have to restore from a backup. I don't know exactly what causes it, but it usually happens when I have some error in my init file, and I end up restarting Emacs several times while trying to fix the error.

It almost seems as if persistent-scratch is not loading the save file, but then saves the empty scratch buffer when I exit Emacs, and then reloads the new, empty save file the next time Emacs is run--but I don't understand how that could happen, since if persistent-scratch gets loaded at all, it should restore the save file in the first place. Nevertheless, it happens. :(

Anyway, my point is that the keep-n-newest-backups filter could cause data-loss in this situation, if the user restarted Emacs more times than the number is set to, without noticing that the scratch buffer is now empty. This happens to me, as I'm focused on the new, strange initialization error instead of the fact that the scratch buffer is empty. I usually end up restarting Emacs several times, finally fixing the error--and only then do I notice that the scratch buffer is empty, and now I have another problem to fix.

**Comment by holocronweaver** [comment] 2017-09-07 15:40
What is your persistent-scratch config?

**Comment by alphapapa** [comment] 2017-09-08 02:05
```el
(custom-set-variables
 '(persistent-scratch-autosave-interval 60)
 '(persistent-scratch-autosave-mode t)
 '(persistent-scratch-backup-directory "~/.emacs.d/backups/scratch"))

(use-package persistent-scratch
  :config (persistent-scratch-setup-default))
```

**Comment by holocronweaver** [comment] 2017-09-09 18:07
Found the bug, have some solutions.

Can reproduce by simply inserting a line of random text just before the config. As @alphapapa says, persistent-scratch seemingly fails to load due to the error, yet somehow the `.persistent-scratch` file is being overwritten.

My config is very similar and also experiences the bug:

```
(use-package persistent-scratch
  :ensure
  :config
  (setq persistent-scratch-backup-directory (concat user-emacs-directory "scratch"))
  (persistent-scratch-setup-default))
```

In my case this only occurs if I am restoring an Emacs desktop. The desktop file restores the modes of all buffers, including `persistent-map-autosave-mode`, but due to the error my custom config was never loaded. This in turn causes `persistent-scratch--turn-autosave-on` to add `persistent-scratch-save` to the  `kill-emacs-hook` as well as an auto-save timer, however `persistent-scratch-restore` is not being called so the scratch buffer will be in its default state. So when you `kill-emacs` or the auto-save timer goes off, `.persistent-scratch` will be overwritten with a default scratch buffer.

One solution is to move:

```
(condition-case err
      (persistent-scratch-restore)
    (error
     (message "Failed to restore scratch buffers: %S" err)
     nil))
```

from `persistent-scratch-setup-default` into `persistent-scratch-autosave-mode`, and setting a flag that ensures the restoration only occurs once per session, not once per buffer with the mode enabled. That should solve the bug.

However I prefer a different solution. Remove all modes since this package doesn't need any as it's just wrapping some global hooks and timers. The user can then toggle functionality by calling interactive functions. That way desktop restoration won't have any effect on this package, so it should not cause any bugs in the foreseeable future. Plus it avoids the redundancy of calling mode code for each buffer, which isn't efficient for non-buffer-specific tasks.

That said, maybe there is some technical reason not to do this I am overlooking?

**Comment by holocronweaver** [comment] 2017-09-09 18:09
@alphapapa Just to confirm my findings, are you using Emacs desktop restoration?

**Comment by alphapapa** [comment] 2017-09-10 02:12
@holocronweaver Wow, excellent work.  I did not have the interest or patience to dig into it, but you did, and very quickly.  :)

> However I prefer a different solution. Remove all modes since this package doesn't need any as it's just wrapping some global hooks and timers. The user can then toggle functionality by calling interactive functions.

That's essentially what a global minor mode is.  I haven't looked at much of persistent-scratch's code, but I guess a global minor mode is how it should be implemented.  But Fanael is an experienced elisp hacker, so if he did it differently, there's probably a reason for that.

> Just to confirm my findings, are you using Emacs desktop restoration?

I have been trying out desktop-mode recently, but I experienced this bug without desktop-mode as well.

**Comment by holocronweaver** [comment] 2018-09-29 06:41
I am unable to reproduce the bug with `desktop-save-mode` disabled, but in principle it could happen any time scratch autosave is turned on and saves before the scratch buffer is restored.

Worth noting this problem does NOT occur when using straight.el instead of package.el. Straight.el only loads packages when user explicitly calls `require` or `use-package`. Thus when the desktop is restored persistent-scratch-autosave-mode is not defined and no overwriting of persistent-scratch file is overwritten.

**Closed as completed** 2018-09-29 14:12 UTC
