### ISSUE TITLE
This feature is already built in

### ISSUE THREAD

**Issue by mina86** [Fanael/persistent-scratch#19] opened 2019-09-05 14:17 UTC
So…
```(require 'remember)
(setq remember-notes-buffer-name "*scratch*"
      initial-buffer-choice (lambda ()
                              (kill-buffer remember-notes-buffer-name)
                              (remember-notes))))
```
already preserves scratch.

**Comment by Fanael** [comment] 2019-09-05 18:22
Duplicate of #3.

**Closed as completed by Fanael** 2019-09-05 18:22 UTC
Labels: duplicate, invalid

**Comment by mina86** [comment] 2019-09-05 18:37
D’oh. Sorry about the noise.
